Support adding books when the read file is empty (#17)
* Support adding books when the read file is empty

If someone uses this github action with an empty read file, it fails
with the following error. By defaulting `readListJson` to an empty
array, one does not have to create the first entry manually.

```
Error: Cannot read properties of undefined (reading 'push')
```

* Prefix the version with v when generating the README